Add item requests
AleksandrRudinskiy/java-shareit pull request #3
Opened 2024-04-19 20:24 UTC by AleksandrRudinskiy

2024-04-24 01:34 UTC, dgumich requested changes

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/dto/ItemRequestDto.java
> +    @NotNull
Зачем сразу две аннотации @NotNull и @NotBlank? Почитай документации к ним, одна из них более строгая, так что хватит её одной.

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/ItemRequestController.java
> +                                     @Validated
Какой смысл использовать @Validated вместо @Valid? Разницу можешь узнать здесь https://www.baeldung.com/spring-valid-vs-validated

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/ItemRequestServiceImpl.java
> +        return ItemRequestMapper.convertToItemRequestDto(
Ну вот сэкономил пару строк и переменных, а читать код легче не стало. Не жалей, вынеси в отдельные переменные/строки кода), а не всё в методы/конструкторы кидать=)

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/ItemRequestServiceImpl.java
> +@Slf4j
А зачем на логгер если мы его не используем?

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/ItemRequestService.java
> +    List<ItemRequestWithItemsDto> getByRequestorId(long userId);
А что get? Где существительное, которое мы возвращаем?=) Так же исправь названия методов у  getById и getAll

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/dto/ItemRequestWithItemsDto.java
> +    @NotNull
Аналогично, две аннотации нам не нужно.

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/dto/ItemRequestDto.java
> +    private LocalDateTime created = LocalDateTime.now();
А зачем мы инициализируем данное поле?

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/request/ItemRequestController.java
> +    public ItemRequestWithItemsDto getById(@RequestHeader(value = "X-Sharer-User-Id") long userId,
Зачем нам  long userId, если по ТЗ:
Посмотреть данные об отдельном запросе может любой пользователь.

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +        List<Item> usersItems = itemRepository.getByOwner_id(userId);
А где пагинация? По тз должна быть.

2024-04-24 01:34 UTC, dgumich commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +            return itemRepository.search(text).stream()
По тз здесь тоже должна быть пагинация

2024-04-24 01:34 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    private ItemRepository itemRepository = Mockito.mock(ItemRepository.class);
Это не интеграционный тест. Ты просто замокал все зависимости, так что работает только один модуль. По ТЗ у нас должно быть:
Реализовать интеграционные тесты, проверяющие взаимодействие с базой данных. Как вы помните, интеграционные тесты представляют собой более высокий уровень тестирования: их обычно требуется меньше, но покрытие каждого — больше. Мы предлагаем вам создать по одному интеграционному тесту для каждого крупного метода в ваших сервисах. Например, для метода getUserItems в классе ItemServiceImpl.

В данном тесте с базой данных мы не работаем, так как классы репозиториев просто замоканы.

2024-04-24 01:34 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    private CommentRepository commentRepository = Mockito.mock(CommentRepository.class);
Так же не хватает тестов по ТЗ:
Реализовать тесты для слоя репозиториев вашего приложения с использованием аннотации @DataJpaTest. Есть смысл написать тесты для тех репозиториев, которые содержат кастомные запросы. Работа с аннотацией @DataJpaTest не рассматривалась подробно в уроке, поэтому вам предстоит изучить пример самостоятельно, [перейдя по ссылке](https://howtodoinjava.com/spring-boot2/testing/datajpatest-annotation/). Ещё больше деталей вы сможете найти в приложенном файле с советами ментора.
Реализовать тесты для работы с JSON для DTO в вашем приложении с помощью аннотации @JsonTest. Такие тесты имеют смысл в тех случаях, когда ваши DTO содержат в себе некоторую логику. Например, описание формата дат или валидацию. Выберите DTO, где есть подобные условия, и напишите тесты.

2024-04-24 07:38 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/dto/ItemRequestDto.java
> +    @NotNull
@NotBlank более строгая, оставил ее.

2024-04-24 07:57 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/ItemRequestController.java
> +                                     @Validated
Понял, @validated это если группа полей, у меня пока такого нет. Поменял на @Valid

2024-04-24 07:58 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/ItemRequestServiceImpl.java
> +        return ItemRequestMapper.convertToItemRequestDto(
Хорошо, спасибо.

2024-04-24 08:01 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/ItemRequestServiceImpl.java
> +@Slf4j
Согласен, убрал аннотацию.

2024-04-24 08:12 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/ItemRequestService.java
> +    List<ItemRequestWithItemsDto> getByRequestorId(long userId);
Согласен. Названия всех трех методов поправил.

2024-04-24 08:53 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/dto/ItemRequestWithItemsDto.java
> +    @NotNull
Оставил только @NotBlank

2024-04-24 09:17 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/dto/ItemRequestDto.java
> +    private LocalDateTime created = LocalDateTime.now();
Для составления Dto, когда POST запрос, то в контроллер Dto json без даты приходит, вот я и ставил инициализацию здесь. Сейчас я убрал из Dto и поставил в Mapper.

2024-04-24 09:22 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/request/ItemRequestController.java
> +    public ItemRequestWithItemsDto getById(@RequestHeader(value = "X-Sharer-User-Id") long userId,
Да, но в тестах постмана есть проверка на userId - он не должен быть не существующим, так что в контроллере я оставил userId.

2024-04-24 09:50 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +            return itemRepository.search(text).stream()
Пагинацию добавил.

2024-04-24 13:42 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +        List<Item> usersItems = itemRepository.getByOwner_id(userId);
Пагинацию добавил.

2024-04-24 22:49 UTC, AleksandrRudinskiy commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    private ItemRepository itemRepository = Mockito.mock(ItemRepository.class);
Добавил интеграционный тест для getUserItems

2024-04-24 22:51 UTC, AleksandrRudinskiy commented on src/test/java/ru/practicum/shareit/item/ItemServiceTest.java
> +    private CommentRepository commentRepository = Mockito.mock(CommentRepository.class);
Тесты с аннотациями @DataJpaTest и  @Jsontest добавил

2024-04-24 22:54 UTC, AleksandrRudinskiy commented
Дмитрий, исправил аннотации, названия методов, добавил пагинацию в классы где их не хватало и тесты на repository и json. В реальности понимаю, что тестов должно быть гораздо больше. Сейчас ориентировался на покрытие 70 % строк.

2024-04-25 21:10 UTC, dgumich requested changes

2024-04-25 21:10 UTC, dgumich commented on src/main/java/ru/practicum/booking/BookingController.java
> +
Лишняя пустая строка=)

2024-04-25 21:10 UTC, dgumich commented on src/main/java/ru/practicum/booking/BookingServiceImpl.java
> +        if (LocalDateTime.parse(bookingDto.getStart())
Условие в блоке вообще не понятно. Не надо пытаться всё записать в одну строку. Вводи переменные, LocalDateTime startDate/EndDate так будет на много лучше и понятней.

2024-04-25 21:10 UTC, dgumich commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +                        .filter(b -> b.getStart().isBefore(NOW_TIME) && bookingRepository.getById(b.getId()).getStatus() == Status.APPROVED)
Сложную логику проверки надо выносить в отдельные методы, тогда стрим становится понятней.

2024-04-25 21:10 UTC, dgumich commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +                        .filter(b -> b.getStart().isAfter(NOW_TIME) && bookingRepository.getById(b.getId()).getStatus() == Status.APPROVED)
Здесь тоже лучше вынести в отдельный метод всю эту проверку
b.getStart().isAfter(NOW_TIME) && bookingRepository.getById(b.getId()).getStatus() == Status.APPROVED

2024-04-25 21:10 UTC, dgumich commented on src/test/java/ru/practicum/shareit/user/UserRepositoryTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(
Должно быть больше тестов для репозиториев:
Реализовать тесты для слоя репозиториев вашего приложения с использованием аннотации @DataJpaTest. Есть смысл написать тесты для тех репозиториев, которые содержат кастомные запросы.

2024-04-25 21:10 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    private final ObjectMapper mapper = new ObjectMapper();
Мапер должен быть в контексте у бута, пробовал внедрять?

2024-04-25 21:10 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +        mvc.perform(get("/items")
Зачем в тесте сервисного слоя MVC? Тут всё как с юнит тестированием: тестируем сервис, значит создаем его, внедряя все нужные "рабочие" зависимости (а не моки) и вызываем нужный метод. Вызывать контроллер не надо

2024-04-25 21:10 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +public class ItemServiceIntegrationTest {
По ТЗ интеграционные тесты должны быть написаны на все сервисы, на самые сложные методы (где больше всего логики):
Реализовать интеграционные тесты, проверяющие взаимодействие с базой данных. Как вы помните, интеграционные тесты представляют собой более высокий уровень тестирования: их обычно требуется меньше, но покрытие каждого — больше. Мы предлагаем вам создать по одному интеграционному тесту для каждого крупного метода в ваших сервисах

2024-04-26 03:54 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/booking/BookingController.java
> +
Убрал

2024-04-26 04:04 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/booking/BookingServiceImpl.java
> +        if (LocalDateTime.parse(bookingDto.getStart())
Ввел переменные endDate и startDate

2024-04-26 06:25 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +                        .filter(b -> b.getStart().isBefore(NOW_TIME) && bookingRepository.getById(b.getId()).getStatus() == Status.APPROVED)
Вынес проверки в методы checkLastBooking и checkNextBooking.

2024-04-26 06:27 UTC, AleksandrRudinskiy commented on src/main/java/ru/practicum/item/ItemServiceImpl.java
> +                        .filter(b -> b.getStart().isAfter(NOW_TIME) && bookingRepository.getById(b.getId()).getStatus() == Status.APPROVED)
Вынес в отдельный метод checkNextBooking().

2024-04-26 13:40 UTC, AleksandrRudinskiy commented on src/test/java/ru/practicum/shareit/user/UserRepositoryTest.java
> +@DataJpaTest(includeFilters = @ComponentScan.Filter(
Добавил тесты на все репозитории

2024-04-26 13:43 UTC, AleksandrRudinskiy commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +        mvc.perform(get("/items")
Я потому что здесь сделал интеграционный тест, просто назвал сервисом, а так у меня есть и с моками, который называется ItemServiceTest

2024-04-26 13:46 UTC, AleksandrRudinskiy commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +public class ItemServiceIntegrationTest {
Вроде у меня интеграционные тесты в классах с названиями ...IntegtionalTest, в одном правда месте интеграционный тест назвал ItemServiceIntegrationTest ))

2024-04-26 14:07 UTC, AleksandrRudinskiy commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    private final ObjectMapper mapper = new ObjectMapper();
В теории написано, что с помощью аннотации @WebMvcTest но у меня не получилось

2024-04-26 14:12 UTC, AleksandrRudinskiy commented
Дмитрий, замечания учел, тесты добавил.

2024-04-27 01:53 UTC, dgumich requested changes

2024-04-27 01:53 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +        mvc.perform(get("/items")
А причём интеграционный тест сервисного слоя и слой контроллеров? Это никак не связанные вещи, MVC тут не должно быть. Не надо вызывать mvc.perform(get("/items"). Это интеграционный тест сервисного слоя, не контроллера. Значит, ты должен создать сервисный класс, и внедрить "рабочие" зависимости (репозиториев и других сервисов, если нужно). Затем вызвать нужный метод у сервиса (как делаем в юнит тестировании). То есть вместо  mvc.perform(get("/items") у тебя должно быть itemService.getUserItems(userId, from, size).
Сейчас получается странно: тест сервиса, но ни самого сервиса нет плюс непонятно, что за метод тестируется. Надо переделать.

2024-04-27 01:53 UTC, dgumich commented on src/test/java/ru/practicum/shareit/item/ItemServiceIntegrationTest.java
> +    private final ObjectMapper mapper = new ObjectMapper();
Не получилось - не ответ разработчика=) Что за ошибка?

2024-05-10 08:01 UTC, merged